export {default as Navbar} from './navbar'
export {default as UserHome} from './user-home'
export {Login, Signup} from './auth-form'
export {default as Personality} from './personalityQuiz'
export {default as Auth} from './auth'

export {default as LandingPage} from './landing-page'
export {default as IntroSection} from './layout/landing/intro-section'
export {default as Curve} from './layout/landing/Curve'
export {default as InfoSection} from './layout/landing/info-section'
export {default as Reviews} from './layout/landing/reviews'
export {default as Access} from './layout/landing/access'
export {default as FooterSection} from './layout/landing/footer-section'
